__title__ = 'nptyping'
__version__ = '1.4.0'
__author__ = 'Ramon Hagenaars'
__author_email__ = 'ramon.hagenaars@gmail.com'
__description__ = 'Type hints for Numpy.'
__url__ = 'https://github.com/ramonhagenaars/nptyping'
__license__ = 'MIT'
